/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "and_gate.v:1.1-9.10" *)
module and_gate(a, b, y);
  (* src = "and_gate.v:2.16-2.17" *)
  input a;
  wire a;
  (* src = "and_gate.v:3.16-3.17" *)
  input b;
  wire b;
  (* src = "and_gate.v:4.17-4.18" *)
  output y;
  wire y;
  assign y = b & a;
endmodule
