name: Makefile CI with HDL Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: kreijstal/install-verilator-action@main

    - name: Install HDL tools and dependencies
      run: |
        sudo apt-get update #unfortunately ghdl-gcc or mcode are not that great for cosim.
        sudo apt-get install -y ghdl-llvm iverilog python3-pip clang llvm
        pip3 install --upgrade pip

    - name: Run make run
      run: make run

  windows-build:
    strategy:
      matrix:
        sys: [MINGW64, UCRT64]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: base-devel git
        pacboy: >-
          ghdl-llvm:p
          iverilog:p
          python-pip:p
          verilator:p

    - name: Run make
      shell: msys2 {0}
      run: make run
