name: Makefile CI with HDL Tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install HDL tools and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator ghdl iverilog python3-pip
        pip3 install --upgrade pip

    - name: Run make run
      run: make run

